### PR TITLE
Downgrade DNS errors to warnings

### PR DESCRIPTION
**Pull request by nightkr**
# Description

After some discussion on Slack (https://stackable-workspace.slack.com/archives/C031A5Z9542/p1733999979523619), treating these as errors might be a bit harsh, given that containerdebug is "only" a diagnostics tool.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by Maleware — APPROVED** [review]
LGTM, modulo checks. Thanks for picking this up right away :)

**Comment by nightkr** [comment]
Yeah the deny is a separate issue we should look into.

**Comment by lfrancke** [comment]
I know I'm late here but considering it's a WARN it'd be helpful if we could give users some context.
Like "shit, there is a warning, what does it mean? is it bad for me? what can I do? What does it mean?"

Not sure if that's possible. Treat it as an idea.

**Comment by nightkr** [comment]
Hmm..

**Pull request merged**
